# Generated by Django 5.1.1 on 2024-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('copyright', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation', models.TextField()),
                ('hdurl', models.URLField()),
            ],
        ),
    ]
